export const pokemonTypesFormArray = [
  { label: 'Normal', value: 'Normal' },
  { label: 'Fire', value: 'Fire' },
  { label: 'Fighting', value: 'Fighting' },
  { label: 'Water', value: 'Water' },
  { label: 'Flying', value: 'Flying' },
  { label: 'Grass', value: 'Grass' },
  { label: 'Poison', value: 'Poison' },
  { label: 'Electric', value: 'Electric' },
  { label: 'Ground', value: 'Ground' },
  { label: 'Psychic', value: 'Psychic' },
  { label: 'Rock', value: 'Rock' },
  { label: 'Ice', value: 'Ice' },
  { label: 'Bug', value: 'Bug' },
  { label: 'Dragon', value: 'Dragon' },
  { label: 'Ghost', value: 'Ghost' },
  { label: 'Dark', value: 'Dark' },
  { label: 'Steel', value: 'Steel' },
  { label: 'Fairy', value: 'Fairy' },
];
